In [1]:
import numpy as np
import pandas as pd

## 1. DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
# shape: returns number of elements in each dimension
# ndim: returns number of array dimensions
# dtype: returns data type of the NumPy array
# size: returns the number of elements in the array

a1 = np.array([1,2,3])
print(a1)
print(type(a1))
print(a1.shape)
print(a1.ndim)
print(a1.dtype)
print(a1.size)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
int64
3


In [3]:
a2 = np.array([[1,2,3], [4,5,6]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2.ndim)
print(a2.dtype)
print(a2.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2
int64
6


In [4]:
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]],
 [[10,11,12],[13,14,15],[16,17,18]],
               [[19,20,21],[22,23,24],[25,26,27]]])
print(a3)
print(type(a3))
print(a3.shape)
print(a3.ndim)
print(a3.dtype)
print(a3.size)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
<class 'numpy.ndarray'>
(3, 3, 3)
3
int64
27


In [5]:
# Create DataFrames from NumPy arrays
# DataFrame is a 2D data structure
df = pd.DataFrame(a2)
print(df)

   0  1  2
0  1  2  3
1  4  5  6


## 2. Creating arrays

In [6]:
sample_array = np.array([1,2,3])
print(sample_array)
print(sample_array.dtype)

[1 2 3]
int64


In [7]:
ones = np.ones((3,3))
print(ones)
print(ones.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


In [8]:
zeros = np.zeros((3,3))
print(zeros)
print(zeros.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [9]:
range_array = np.arange(0, 10, 2)
print(range_array)
print(range_array.dtype)

[0 2 4 6 8]
int64


In [10]:
random_array = np.random.randint(0, 10, size = (3,3))
print(random_array)
print(range_array.dtype)

[[7 8 3]
 [3 7 6]
 [4 2 3]]
int64


In [11]:
random_array_rand = np.random.rand(3,3)
print(random_array_rand)
print(range_array.dtype)

[[0.11544052 0.45019048 0.42966591]
 [0.33896221 0.70860028 0.70969235]
 [0.68111256 0.08980873 0.46617246]]
int64


In [13]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_1 = np.random.randint(10, size=(3,3))
print(random_array_1)
print(random_array_1.shape)

[[5 0 3]
 [3 7 9]
 [3 5 2]]
(3, 3)


In [14]:
np.random.seed(seed=7)
random_array_2 = np.random.random((3,3))
print(random_array_2)
print(random_array_2.shape)

[[0.07630829 0.77991879 0.43840923]
 [0.72346518 0.97798951 0.53849587]
 [0.50112046 0.07205113 0.26843898]]
(3, 3)
