<a href="https://colab.research.google.com/github/UnrivalledHitman120703/Machine-Learning-and-Data-Science-Bootcamp/blob/main/Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

## 1. DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
# shape: returns number of elements in each dimension
# ndim: returns number of array dimensions
# dtype: returns data type of the NumPy array
# size: returns the number of elements in the array

a1 = np.array([1,2,3])
print(a1)
print(type(a1))
print(a1.shape)
print(a1.ndim)
print(a1.dtype)
print(a1.size)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
int64
3


In [3]:
a2 = np.array([[1,2,3], [4,5,6]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2.ndim)
print(a2.dtype)
print(a2.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2
int64
6


In [4]:
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]],
 [[10,11,12],[13,14,15],[16,17,18]],
               [[19,20,21],[22,23,24],[25,26,27]]])
print(a3)
print(type(a3))
print(a3.shape)
print(a3.ndim)
print(a3.dtype)
print(a3.size)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
<class 'numpy.ndarray'>
(3, 3, 3)
3
int64
27


In [5]:
# Create DataFrames from NumPy arrays
# DataFrame is a 2D data structure
df = pd.DataFrame(a2)
print(df)

   0  1  2
0  1  2  3
1  4  5  6


## 2. Creating arrays

In [6]:
sample_array = np.array([1,2,3])
print(sample_array)
print(sample_array.dtype)

[1 2 3]
int64


In [7]:
ones = np.ones((3,3))
print(ones)
print(ones.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


In [8]:
zeros = np.zeros((3,3))
print(zeros)
print(zeros.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [9]:
range_array = np.arange(0, 10, 2)
print(range_array)
print(range_array.dtype)

[0 2 4 6 8]
int64


In [10]:
random_array = np.random.randint(0, 10, size = (3,3))
print(random_array)
print(range_array.dtype)

[[3 6 8]
 [9 9 0]
 [2 3 3]]
int64


In [11]:
random_array_rand = np.random.rand(3,3)
print(random_array_rand)
print(range_array.dtype)

[[0.17639218 0.53991171 0.50992253]
 [0.34634418 0.960957   0.32467127]
 [0.49564997 0.99266717 0.18840425]]
int64


In [12]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_1 = np.random.randint(10, size=(3,3))
print(random_array_1)
print(random_array_1.shape)

[[5 0 3]
 [3 7 9]
 [3 5 2]]
(3, 3)


In [13]:
np.random.seed(seed=7)
random_array_2 = np.random.random((3,3))
print(random_array_2)
print(random_array_2.shape)

[[0.07630829 0.77991879 0.43840923]
 [0.72346518 0.97798951 0.53849587]
 [0.50112046 0.07205113 0.26843898]]
(3, 3)


## 3. Viewing Arrays and Matrices

In [14]:
random_array_3 = np.unique(random_array_1)
print(random_array_3)

[0 2 3 5 7 9]


In [15]:
random_array_4 = np.random.randint(10, size = (2,3,4,5))
print(random_array_4)
print(random_array_4.shape)
print(random_array_4.ndim)

[[[[7 6 4 0 7]
   [0 7 6 3 5]
   [8 8 7 5 0]
   [0 2 8 9 6]]

  [[4 9 7 3 3]
   [8 3 0 1 0]
   [0 6 7 7 9]
   [3 0 7 7 7]]

  [[0 5 4 3 1]
   [3 1 3 4 3]
   [1 9 5 9 1]
   [2 3 2 2 5]]]


 [[[7 3 0 9 9]
   [3 4 5 3 0]
   [4 8 6 7 2]
   [7 3 8 6 6]]

  [[5 6 5 7 1]
   [5 4 4 9 9]
   [0 6 2 6 8]
   [2 4 1 6 1]]

  [[5 1 6 9 8]
   [6 5 9 7 5]
   [4 9 6 8 1]
   [5 5 8 3 7]]]]
(2, 3, 4, 5)
4


In [16]:
# Get the first 4 numbers of the inner most arrays
print(random_array_4[:, :, :, :1])

[[[[7]
   [0]
   [8]
   [0]]

  [[4]
   [8]
   [0]
   [3]]

  [[0]
   [3]
   [1]
   [2]]]


 [[[7]
   [3]
   [4]
   [7]]

  [[5]
   [5]
   [0]
   [2]]

  [[5]
   [6]
   [4]
   [5]]]]


## 4. Manipulating & comparing arrays

### Arithmetic

In [17]:
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [18]:
ones = np.ones(3)
print(ones)

[1. 1. 1.]


In [19]:
print(a1 + ones)

[2. 3. 4.]


In [20]:
print(a1 - ones)

[0. 1. 2.]


In [21]:
print(a1 * ones)

[1. 2. 3.]


In [22]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])
print(a2)

[[1.  2.  3.3]
 [4.  5.  6.5]]


In [23]:
print(a1 * a2)

[[ 1.   4.   9.9]
 [ 4.  10.  19.5]]


In [24]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[10,11,12],[13,14,15],[16,17,18]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [25]:
# Reshaping a2 to be multiplicably compatible with a3
a2_reshaped = a2[:, :, np.newaxis]
print(a2_reshaped * a3)

[[[  1.    2.    3. ]
  [  8.   10.   12. ]
  [ 23.1  26.4  29.7]]

 [[ 40.   44.   48. ]
  [ 65.   70.   75. ]
  [104.  110.5 117. ]]]


In [26]:
print(a1 / ones)

[1. 2. 3.]


In [27]:
print(a2/a1)

[[1.         1.         1.1       ]
 [4.         2.5        2.16666667]]


In [28]:
# Floor division removes the decimals (rounds down)
print(a2//a1)

[[1. 1. 1.]
 [4. 2. 2.]]


In [29]:
print(a2 ** 2)

[[ 1.    4.   10.89]
 [16.   25.   42.25]]


In [30]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [31]:
print(a1 + ones)

[2. 3. 4.]


In [32]:
np.add(a1, ones)

array([2., 3., 4.])

In [33]:
print(a1 / 2)

[0.5 1.  1.5]


In [34]:
print(a2 % 2)

[[1.  0.  1.3]
 [0.  1.  0.5]]


In [35]:
print(np.exp(a1))

[ 2.71828183  7.3890561  20.08553692]


In [36]:
print(np.log(a1))

[0.         0.69314718 1.09861229]


### Aggregation
Aggregation = Performing the same operation on a number of things

In [37]:
listy_list = [1,2,3]
type(listy_list)

list

In [38]:
sum(listy_list)

6

In [39]:
sum(a1)

6

In [40]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Python datatypes and use Numpy's methods on Numpy arrays (`np.sum()`).

In [41]:
# Creating a massive NumPy array
massive_array = np.random.random(100000)
print(massive_array.size)
print(massive_array[:10])

100000
[0.75778036 0.513401   0.17842575 0.39200156 0.93959276 0.21291858
 0.81329627 0.40364858 0.58672092 0.18599889]


In [42]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

9.9 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
60.1 µs ± 16.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [43]:
print(np.mean(a2))

3.6333333333333333


In [44]:
print(np.max(a2))

6.5


In [45]:
print(np.min(a2))

1.0


**Standard deviation** and **variance** are measures of 'spread' of data.

The higher standard deviation and the higher variance of data, the more spread out the values are.

The lower standard deviation and lower variance, the less spread out the values are.

In [46]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [47]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [48]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422

In [49]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [50]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [51]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

In [52]:
np.mean(high_var_array), np.mean(low_var_array)

(1600.1666666666667, 6.0)