In [9]:
import numpy as np
import pandas as pd

## DataTypes & Attributes

In [6]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
print(a1)
print(type(a1))
print(a1.shape)
print(a1.ndim)
print(a1.dtype)
print(a1.size)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
int64


In [7]:
a2 = np.array([[1,2,3], [4,5,6]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2.ndim)
print(a2.dtype)
print(a2.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2
int64


In [8]:
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]],
 [[10,11,12],[13,14,15],[16,17,18]],
               [[19,20,21],[22,23,24],[25,26,27]]])
print(a3)
print(type(a3))
print(a3.shape)
print(a3.ndim)
print(a3.dtype)
print(a3.size)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
<class 'numpy.ndarray'>
(3, 3, 3)
3
int64


In [14]:
# Create DataFrames from NumPy arrays
df = pd.DataFrame(a2)
print(df)

   0  1  2
0  1  2  3
1  4  5  6
